services:
  steam:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["/steam/entrypoint.sh"]
    volumes:
      - ./steam:/steam
      - ./resultados:/resultados
      - ./tiktok_upload:/tiktok_upload
